config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "memos#index"
  resources :memos, only: [:index, :new, :create, :destroy,:edit,:update]
  resources :capacities, only: [:index, :new, :create]
  resources :orders, only: [:index]
  resources :apartments, only: [:index]
  resources :not_orderings, only: [:index]
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  validates :apartment_number, presence: true
  validates :room_number, presence: true
  validates :postal_code, presence: true
  validates :client_number, presence: true
  validates :client_name, presence: true
  has_one :order
  has_one :not_ordering
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capacity.rb
class Capacity < ApplicationRecord
  validates :client_number, presence: true, length: { minimum: 4, message: 'is too short (minimum is 4 characters)' },
                            numericality: { only_integer: true, message: 'is not a number' }, uniqueness: true
  validates :client_name, presence: true
  validates :capacity, presence: true, numericality: { only_integer: true, message: 'is not a number' }
end

app/models/memo.rb
class Memo < ApplicationRecord
  validates :title, presence: true
  validates :memo, presence: true
  belongs_to :user
end

app/models/not_ordering.rb
class NotOrdering < ApplicationRecord
  belongs_to :apartment
  belongs_to :capacity
end

app/models/order.rb
class Order < ApplicationRecord
  validates :order_number, presence: true
  validates :status, presence: true
  validates :order_date, presence: true
  validates :deadline_date, presence: true
  belongs_to :apartment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :memos
  validates :nickname, presence: true, length: { maximum: 10 }
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @apartments = Apartment.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/capacities_controller.rb
class CapacitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @capacities = Capacity.all
  end

  def new
    @capacity = Capacity.new
  end

  def create
    @capacity = Capacity.new(capacity_params)
    return redirect_to capacities_path if @capacity.save

    render 'new'
  end

  private

  def capacity_params
    params.require(:capacity).permit(:client_number, :client_name, :capacity, :remarks)
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :update]
  before_action :set_memo, only: [:edit, :update, :destroy]
  before_action :move_to_index, except: [:index]

  def index
    @memos = Memo.all.order('created_at DESC')
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.new(memo_params)
    return redirect_to root_path if @memo.save

    render 'new'
  end

  def edit
    set_memo
  end

  def update
    return redirect_to root_path if @memo.update(memo_params)

    render 'edit'
  end

  def destroy
    return unless @memo.destroy

    redirect_to root_path
  end

  private

  def memo_params
    params.require(:memo).permit(:title, :memo).merge(user_id: current_user.id)
  end

  def set_memo
    @memo = Memo.find(params[:id])
  end

  def move_to_index
    return if user_signed_in?

    redirect_to action: :index
  end
end

app/controllers/not_orderings_controller.rb
class NotOrderingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @not_orderings = NotOrdering.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = Order.all
  end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capacities_helper.rb
module CapacitiesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/not_orderings_helper.rb
module NotOrderingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/apartments/index.html.erb
<%= render "shared/header" %>

<div class="contents">
  <div class="contents row">
    <p>物件一覧</p>
    <table border="1" style="border-collapse: collapse;">
      <thead>
        <tr>
          <th>AP番号</th>
          <th>号室</th>
          <th>郵便番号</th>
          <th>住所</th>
          <th>業者コード</th>
          <th>業者名</th>
        </tr>
      </thead>
      <% @apartments.each do |apartment| %>
        <div class="content_post" >
          <tr>
            <th><%= apartment.apartment_number %></th>
            <th><%= apartment.room_number %></th>
            <th><%= apartment.postal_code %></th>
            <th><%= apartment.address %></th>
            <th><%= apartment.client_number %></th>
            <th><%= apartment.client_name %></th>
          </tr>
        </div>
      <% end %>
    </table>
  </div>
</div>

<%= render "shared/footer" %>

app/views/capacities/index.html.erb
<%= render "shared/header" %>

<div class="contents">
  <div class="contents row">
    <p>登録業者一覧</p>
    <table border="1" style="border-collapse: collapse;">
      <thead>
        <tr>
          <th>業者コード</th>
          <th>業者名</th>
          <th>キャパシティ</th>
          <th>備考</th>
        </tr>
      </thead>
      <% @capacities.each do |capacity| %>
        <div class="content_post" >
          <tr>
            <th><%= capacity.client_number %></th>
            <th><%= capacity.client_name %></th>
            <th><%= capacity.capacity %></th>
            <th><%= capacity.remarks %></th>
          </tr>
        </div>
      <% end %>
    </table>
  </div>
</div>

<%= render "shared/footer" %>

app/views/capacities/new.html.erb
<%= render "shared/header" %>

<div class="contents">
  <div class="contents row">
    <p>業者新規登録</p>
      <%= form_with(model: @capacity, local: true) do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
          <table border="1" style="border-collapse: collapse;">
            <thead>
              <tr>
                <th><%= f.label :client_number, '業者コード' %></th>
                <th><%= f.label :client_name, '業者名' %></th>
                <th><%= f.label :capacity, 'キャパシティ' %></th>
                <th><%= f.label :remarks, '備考' %></th>
              </tr>
            </thead>
            <div class="content_post" >
              <tr>
                <th><%= f.text_field :client_number, placeholder: "必須（数字）", :class =>"text_box" %></th>
                <th><%= f.text_field :client_name, placeholder: "必須", :class =>"text_box" %></th>
                <th><%= f.text_field :capacity, placeholder: "必須（数字）", :class =>"text_box" %></th>
                <th><%= f.text_field :remarks, placeholder: "備考(任意)", :class =>"text_box" %></th>
              </tr>
            </div>
          </table>
        <%= f.submit "登録", class:"new-memo-submit_btn" %>
      <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/edit.html.erb
<%= render "shared/header" %>

<div class="post-memo-form">
  <%= form_with(model: @memo, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <p><%= f.label :title, 'メモ名' %><span>（必須・20文字以内）</span></p>
    <%= f.text_field :title, class:"new-memo-title", placeholder: "メモ名" %>
    <p><%= f.label :memo, 'メモの内容' %><span>（必須）</span></p>
    <%= f.text_area :memo, class:"new-memo-content", placeholder: "メモの内容" %>
    <%= f.submit "修正", class:"new-memo-submit_btn" %>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/memos/index.html.erb
<%= render "shared/header" %>

<div class="main-contents">
  <div class="memos">
    <% @memos.each do |memo| %>
        <p class="memo-title">
          <%= memo.title %>
        </p>
        <p class= "memo-content">
          <%= memo.memo%>
        </p>
        <div class="memo-information">
          <p class="memo-post-date">
            <%= memo.created_at.strftime("%Y年 %m月 %d日") %>
          </p>
          <p class="memo-name">
            <%= memo.user.nickname %>
          </p>
          <div class="memo-check">
            <% if user_signed_in? && current_user.id == memo.user_id %>
              <div class="memo-check-button" >
                <%= link_to '編集', edit_memo_path(memo.id), method: :get %>
              </div>
              <div class="memo-check-button" >
                <%= link_to '削除', memo_path(memo.id), method: :delete %>
              </div>
            <% end %>
          </div>
        </div>

    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/memos/new.html.erb
<%= render "shared/header" %>

<div class="post-memo-form">
  <%= form_with(model: @memo, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <p><%= f.label :title, 'メモ名' %><span>（必須・20文字以内）</span></p>
    <%= f.text_field :title, class:"new-memo-title", placeholder: "メモ名" %>
    <p><%= f.label :memo, 'メモの内容' %><span>（必須）</span></p>
    <%= f.text_area :memo, class:"new-memo-content", placeholder: "メモの内容" %>
    <%= f.submit "投稿", class:"new-memo-submit_btn" %>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/not_orderings/index.html.erb
<%= render "shared/header" %>

<div class="contents">
  <div class="contents row">
    <p>物件検索</p>
    
    <div class="address_box">
      <input id="address" type="textbox" value="地名入力">
      <input type="button" value="更新" onclick="codeAddress()">
    </div>
    
        <div id='map'></div>

        <script>
        let map

        function initMap(){
          geocoder = new google.maps.Geocoder()

          map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: 35.667379, lng:139.7054965},
            zoom: 16,
          });

          marker = new google.maps.Marker({
            position:  {lat: 35.667379, lng:139.7054965},
            map: map
          });
        }
        
        let geocoder

        function codeAddress(){
          let inputAddress = document.getElementById('address').value;

          geocoder.geocode( { 'address': inputAddress}, function(results, status) {
            if (status == 'OK') {
              map.setCenter(results[0].geometry.location);
              var marker = new google.maps.Marker({
                  map: map,
                  position: results[0].geometry.location
              });
            } else {
              alert('該当する結果がありませんでした：' + status);
            }
          });   
        }
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>
  </div>

  <div class="contents row">
    <p>未発注物件一覧</p>
    <table border="1" style="border-collapse: collapse;">
      <thead>
        <tr>
          <th>AP番号</th>
          <th>号室</th>
          <th>郵便番号</th>
          <th>住所</th>
          <th>業者コード</th>
          <th>業者名</th>
        </tr>
      </thead>
      <% @not_orderings.each do |not_ordering| %>
        <div class="content_post" >
          <tr>
            <th><%= not_ordering.apartment[:apartment_number] %></th>
            <th><%= not_ordering.apartment[:room_number] %></th>
            <th><%= not_ordering.apartment[:postal_code] %></th>
            <th><%= not_ordering.apartment[:address] %></th>
            <th><%= not_ordering.apartment[:client_number] %></th>
            <th><%= not_ordering.apartment[:client_name] %></th>
          </tr>
        </div>
      <% end %>
    </table>
  </div>

</div>

<%= render "shared/footer" %>

app/views/orders/index.html.erb
<%= render "shared/header" %>

require 'date'

<div class="contents">
  <div class="contents row">
    <p>発注一覧</p>
    <table border="1" style="border-collapse: collapse;">
      <thead>
        <tr>
          <th>AP番号</th>
          <th>号室</th>
          <th>郵便番号</th>
          <th>住所</th>
          <th>業者コード</th>
          <th>業者名</th>
          <th>発注番号</th>
          <th>ステータス</th>
          <th>発注日</th>
          <th>納期</th>
          <th>遅延日数</th>
        </tr>
      </thead>
      <% @orders.each do |order| %>
        <div class="content_post" >
          <tr>
            <th><%= order.apartment[:apartment_number] %></th>
            <th><%= order.apartment[:room_number] %></th>
            <th><%= order.apartment[:postal_code] %></th>
            <th><%= order.apartment[:address] %></th>
            <th><%= order.apartment[:client_number] %></th>
            <th><%= order.apartment[:client_name] %></th>
            <th><%= order.order_number %></th>
            <th><%= order.status %></th>
            <th><%= order.order_date %></th>
            <th><%= order.deadline_date %></th>

            <% if order.status == "完了" || (Date.current - order.deadline_date).to_i < 0 %>
              <th><%= 0 %></th>
            <% else %>
              <th><span><%= (Date.current - order.deadline_date).to_i %></span></th>
            <% end %>
            
          </tr>
        </div>
      <% end %>
    </table>
  </div>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <b>Order App</b>
</div>

app/views/shared/_header.html.erb
<div class="header"> 
  <div class="logo">
    <a href="/"><b>Order App</b></a>
  </div>
  <div class="header-btn">
    <% if user_signed_in? %>
      <%= link_to current_user.nickname + " さんようこそ" ,'/',class:"login-nickname" %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"logout-btn"%>
    <% else %>
      <%= link_to '新規登録', new_user_registration_path, class:"logout-btn" %>
      <%= link_to 'ログイン', new_user_session_path, class:"logout-btn" %>
    <% end %>
  </div>
  <div class="menu-bar">
    <ul class="menu-elements">
      <li id="menu1">
        発注管理
        <ul class="menu1-lists hidden" id="menu1-pull-down">
          <li><%= link_to '発注済み一覧' ,orders_path %></li>
          <li><%= link_to '未発注物件' ,not_orderings_path %></li>
          <li><%= link_to '物件一覧' ,apartments_path %></li>
        </ul>
      </li>
      <li id="menu2">
        業者管理
        <ul class="menu2-lists hidden" id="menu2-pull-down">
          <li><%= link_to '業者登録' ,new_capacity_path %></li>
          <li><%= link_to '業者一覧' ,capacities_path %></li>
        </ul>
      </li>
      <li id="menu3">
        メモ管理
        <ul class="menu3-lists hidden" id="menu3-pull-down">
          <li><%= link_to 'メモ作成' ,new_memo_path %></li>
        </ul>
      </li>
      <li id="menu4">
        ユーザー管理
        <ul class="menu4-lists hidden" id="menu4-pull-down">
          <li><%= link_to 'ユーザー一覧' ,'/' %></li>
            <% if user_signed_in? && current_user.admin? %>
              <li><%= link_to 'ユーザー登録' ,'/', class: "post" %></li>
              <li><%= link_to 'ユーザー編集' ,'/', class: "post" %></li>
            <% end %>
        </ul>
      </li>   
    </ul>
  </div>
</div>